src/components/Tasks.vue
=> Made buttons look like buttons.

src/components/AddCommitteeMemberModal.vue, src/components/CommitteeAdmin.vue, src/pages/Admin.vue
Fixed issue with autocomplete:
=> Fixed autocomplete

src/components/AddCommitteeMemberModal.vue, src/components/Tasks.vue
Fixes simple suggest issues when building the frontend.
=> Fixed build issues

src/App.vue
**In This Pull Request**
- Changed beforeCreate() to beforeMount() so authentication check happens before any component in the website is loaded.
=> TT-113: Concurrency error in FE.

src/components/MinutesThumbnail.vue, src/pages/Committee.vue, src/pages/Minutes.vue, src/router/index.js
**In this Pull Request**
- Modified Minutes Thumbnail to show real data.
- Modified router to minute instead of minutes.
=> TT-118: Get minutes in committee page (FE)

src/pages/Committee.vue
Changed line 25 in committee.vue to label the selector minutes instead of meetings
=> Changed meetings to minutes in committee.vue

src/components/MinutesControls.vue, src/pages/Minutes.vue
**In this Pull Request**
- Added dropdown to add charges to a minute.
- Added list to see charges added to a minute.
- Added option to remove charge added to a minute.
=> TT-111: Drop down for Relevant Charges on Minutes Page

src/components/CommitteesMenu.vue, src/pages/Admin.vue, src/pages/Committee.vue
Pushed committee title to committee page where the description was
=> TT-124, TT-122: Remove Staff Council and other dropdown categories

src/components/MinutesControls.vue, src/mixins/auth.js, src/pages/Charge.vue, src/pages/Committee.vue, src/pages/Minutes.vue
- Created promise to wait for token.
=> TT-125: Concurrency issue still showing up (FE)

src/pages/Committee.vue, src/pages/Minutes.vue
Changed lines 24 and 25 in committee.vue to change the cursor to a pointing hand when the user mouses over the charges and meetings buttons.
=> TT-120: Modify cursor in Charges/Minutes selector so people know they're buttons. (FE)

src/components/AddCommitteeMemberModal.vue
**Things to do:**
Add select in modal that has the options NormalMember, ActiveMember and MinuteTaker
send “role” to backend in add_member_committee with the selected value.
File: components/AddCommitteeMemberModal.vue
**Solution**
=> [TT-130] Client isn't sending member role in Create Members to backend (FE)

src/components/AddCommitteeMemberModal.vue
=> Fixed the role selection arrow not in box

src/components/MinutesControls.vue, src/pages/Admin.vue
=> Added a margin around the buttons

src/pages/Charge.vue
The button works as expected and looks the same as before
=> Implemented redirect button

package-lock.json, package.json, src/components/MinutesControls.vue
[Ticket](https://ritservices.atlassian.net/browse/TT-151)
If charge is closed, it should not be able to be added to minutes, after its closure date. Check for duplicate entries on charge tagging in minutes
The solution I took to fix this issue was a filter on the charges to remove them from showing up.
No additional tests should be needed at this time but implementation/removal of this addition should change if charge deletion is added.
=> [TT-151] - Remove stopped charges from relevant charges in minutes

package-lock.json, package.json, src/pages/Committee.vue
[Ticket](https://ritservices.atlassian.net/browse/TT-154)
Committee meeting location and date not shown on committee banner with the title.
I added the committee fields required in the banner and styled them similarly to the title field above. The current implementation can be condensed a bit so I will probably add that right away.
No tests should be necessary.
=> [TT-154] - Add committee meeting location and date

.travis.yml, package-lock.json, package.json, src/components/AddCommitteeMemberModal.vue, src/components/ChargeAdmin.vue, src/components/CommitteeMembers.vue, src/components/HeaderMenu.vue, src/components/MinutesControls.vue, src/mixins/auth.js, src/pages/Admin.vue, src/pages/Committee.vue
This is the implementation of continuous deployment.
=> Feature - ci cd

src/components/CommitteeAdmin.vue, src/components/CommitteeMembers.vue, src/pages/Committee.vue
https://ritservices.atlassian.net/browse/TT-217
Previously the CommitteeAdmin component was not being displayed to committee members who are not committee heads. This PR changes it so normal committee members can see the component, but only shows the New Minutes button.
=> TT-217 - Allow normal committee members to create minutes

.travis.yml
=> Implementation of CICD

src/components/CommitteesMenu.vue
Added a key attribute for a v-for loop to prevent console warnings.
=> TT-228 - Added key attribute to v-for loop

src/components/MinuteTaskModal.vue, src/components/MinutesControls.vue, src/pages/Minutes.vue
https://ritservices.atlassian.net/browse/TT-110
This ticket allows a user to create a new task while creating or editing a minute. There is a button that opens a modal similar to the `CreateTaskModal` component but allows them to specify a charge. There are no further tests because it makes use of the preexisting backend logic to create a task.
=> TT-110 - Create New Task from Minute Page

src/components/Tasks.vue
https://ritservices.atlassian.net/browse/TT-232
On the charge page there is a button that allows a user to create a new task associated with that charge. If you are not a member of the committee or not logged in, you are still able to click on this button which brings up the modal to create a new task. This PR adds a flag so that Vue will not render this button if you are not a part of the committee or an admin.
=> TT-232 - Visibility of New Task Button

package-lock.json, src/components/ChargeAdmin.vue, src/components/CommitteeAdmin.vue, src/components/CreateTaskModal.vue, src/components/MinuteTaskModal.vue, src/pages/Admin.vue
This ticket adds a few `maxlength` constraints on inputs on the frontend.
=> TT-229 - Frontend Input Constraints

package-lock.json, package.json, test/unit/specs/components/Modal.spec.js
This ticket adds some unit tests to the frontend. I figured it would be a good place to start because it is nearly a functional component and has few edge cases.
=> TT-237 - Modal Component Unit Tests
